@echo off
echo Activating Virtual Environment...
call .venv\Scripts\activate

echo Starting FastAPI Backend...
start "FastAPI Backend" cmd /k "cd backend && uvicorn app.main:app --reload"

echo Starting Celery Worker...
start "Celery Worker" cmd /k "cd backend && celery -A app.worker.celery_app.celery_app worker --loglevel=info --pool=solo"

echo Starting Next.js Frontend...
start "Next.js Frontend" cmd /k "cd frontend && npm run dev"